name: Trigger auto deployment for ptu-cost-compare

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/ptu-cost-compare-AutoDeployTrigger-26071985-3ddf-409a-bc74-89100b842651.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.PTUCOSTCOMPARE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.PTUCOSTCOMPARE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.PTUCOSTCOMPARE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.PTUCOSTCOMPARE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.PTUCOSTCOMPARE_REGISTRY_PASSWORD }}
          containerAppName: ptu-cost-compare
          resourceGroup: minggu-VM
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


